# Main site info
author: Leonardo Uieda
email: uieda@usp.br
url: "https://www.leouieda.com"
site_name: Leonardo Uieda
site_description: Geophysicist, Educator, Scientist, Programmer, Dad
brand: LEONARDO UIEDA
language: en
keywords: 'science, geoscience, geophysics, software, open-source'
repository: leouieda/website
repository_branch: main
favicon: images/favicon.png
thumbnail: images/thumbnail.jpg
license_notice: |
  Except where otherwise noted, all content is licensed
  <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a>.
coc: https://github.com/leouieda/website/blob/main/CODE_OF_CONDUCT.md

# Social media
github: leouieda
mastodon: leouieda
mastodon_server: scicomm.xyz
matrix: "@leouieda:matrix.org"
linkedin: uieda
youtube: leouieda
orcid: 0000-0001-6123-9515
researcherid: G-3258-2012
lattes: "8939551682050504"
researchgate: https://www.researchgate.net/profile/Leonardo-Uieda
googlescholar: http://scholar.google.com/citations?user=qfmPrUEAAAAJ
figshare: https://figshare.com/authors/Leonardo_Uieda/97471

links:
  compgeolab: https://www.compgeolab.org
  fatiando: https://www.fatiando.org
  pygmt: https://www.pygmt.org
  gmt: https://www.generic-mapping-tools.org
  swung: https://softwareunderground.org

# Menu
navigation:
  - name: Home
    id: index
  - name: Blog
    id: blog/index
  - name: Software
    id: software/index
  - name: CV
    id: cv/index
  - name: Contact
    id: contact/index

# Don't copy or process these files
ignore:
  - README.md
  - LICENSE.md
  - CODE_OF_CONDUCT.md
  - environment.yml
  - requirements.txt
  - Makefile
  - css/academicons/README.md
  - giscus.json

# My co-authors
coauthors:
  Me: Uieda, L
  Val: Barbosa, VCF
  Bi: Oliveira Jr, VC
  Paul: Wessel, P
  Joaquim: Luis, J
  Remko: Scharroo, R
  Florian: Wobbe, F
  Walter: Smith, WHF
  Dongdong: Tian, D
  Bridget: Smith-Konter, B
  Eric: Xu, X
  David: Sandwell, DT
  Carla: Braitenberg, C
  Naomi: Ussami, N
  Manoel: D'Agrella-Filho, MS
  JB: Silva, JBC
  Dai: Sales, DP
  Figura: Melo, FF
  Dio: Carlos, DU
  BragaVale: Braga, MA
  YLi: Li, Y
  Angeli: Angeli, G
  Peres: Peres, G
  Everton: Bomfim, EP
  Eder: Molina, E
  Gomes: Gomes, AAS
  Santiago: Soler, SR
  Agustina: Pesce, A
  Gimenez: Gimenez, ME
  Kristoffer: Hallam, KAT
  Guangdong: Zhao, G
  Bo: Chen, B
  JLiu: Liu, J
  LChen: Chen, L
  RGuo: Guo, R
  MKaban: Kaban, MK
  Lindsey: Heagy, LJ
  Lion: Krischer, L
  FWagner: Wagner, F
  Rene: Gassmoeller, R
  Bane: Sullivan, CB
  Jens: Klump, JF
  LBarba: Barba, LA
  JBazan: Bazan, J
  JBrown: Brown, J
  RGuimera: Guimera, RV
  MGymrek: Gymrek, M
  AHanna: Alex Hanna
  KHuff: Huff, KD
  DKatz: Katz, DS
  CMadan: Madan, CR
  KMoerman: Moerman, KM
  KNiemeyer: Niemeyer, KE
  JPoulson: Poulson, JL
  PPrins: Prins, P
  KRam: Ram, K
  ARokem: Rokem, A
  Arfon: Smith, AM
  GThiruvathukal: Thiruvathukal, GK
  KThyng: Thyng, KM
  BWilson: Wilson, BE
  Yehudi: Yehudi, Y
  Remi: Rampin, R
  Hugo: van Kemenade, H
  MattTurk: Turk, M
  Shapero: Shapero, D
  Anderson: Banihirwe, A
  Leeman: Leeman, J
  JEbbing: Ebbing, J
  AGuy: Guy, A
  JFarquharson: Farquharson, J
  AKushnir: Kushnir, A
  FWadsworth: Wadsworth, F
  LPerozzi: Perozzi, L
  MWieczorek: Wieczorek, MA
  LLi: Li, L
  Ricardo: Trindade, RIF
  Gelson: Souza Junior, GF
  Janine: Carmo, J
  Roger: Fu, R
  RNijzink: Nijzink, RC
  NDrost: Drost, N
  FPianosi: Pianosi, F
  SSchymanski: Schymanski, S
  MTso: Tso, M
  Max: Jones, M
  WeiJi: Leong, WJ
  ABelem: Belem, A
  Sacek: Sacek, V
  Bianchi: Bianchi, M
