name: urubu
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - pip
    - livereload
    - jinja2>=2.7
    - beautifulsoup4
    - markdown<3
    - pygments
    - pyyaml
    - pip:
        - urubu==1.3.1
